language: python

dist: trusty

python:
  - "2.7"
  - "3.5"

services:
  - docker

before_install:
  - sudo apt-get -qq update

env:
  global:
    - PATH=$PATH:$HOME/.minimesos/bin

install:
  - curl -sSL https://minimesos.org/install | sh
  - pip install -r requirements.txt

script:
  - py.test --cov=lib/marathon_autoscaler/
  - docker build -t marathon-autoscaler:localbuild .
  - minimesos up
  - minimesos info
  - env
  - eval $(minimesos info | tail -n +3)
  - curl $MINIMESOS_MARATHON/v2/apps

after_script:
  - minimesos destroy