language: python

sudo: required
dist: trusty

services:
  - docker

before_install:
  - sudo apt-get -qq update

env:
  global:
    - PATH=$PATH:$HOME/.minimesos/bin
    - PYENV_VERSION=3.5.2

install:
  - curl -sSL https://minimesos.org/install | sh
  - pip install -r requirements.txt

script:
  - minimesos init
  - minimesos up
  - py.test --cov=lib/marathon_autoscaler/

after_script:
  - minimesos destroy